name: indexed tests
on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mattpolzin2/idris-docker:nightly

    env:
      IDRIS2_CG: chez

    steps:
      - name: Install Dependencies
        run: apt-get update && apt-get -y install git libc6-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build indexed
        run: make && make install
      - name: Test indexed
        run: make test INTERACTIVE=''

